#!/bin/sh

prefix=/usr/local
chroot_path=/compat/ubuntu
ubuntu_version=focal

bindir="${prefix}/bin"
appsdir="${prefix}/share/applications"
chroot_bindir="${chroot_path}/bin"
chroot_libx86_64dir="${chroot_path}/lib/x86_64-linux-gnu"
chroot_lib64dir="${chroot_path}/lib64"

libbsd_dir="build/libbsd"
libbsd_repo="https://github.com/wulf7/linux-libbsd.git"
libbsd_kmod="linux_libbsd"

obsidian_ver="1.0.3"
obsidian_deb="obsidian_${obsidian_ver}_amd64.deb"
obsidian_url="https://github.com/obsidianmd/obsidian-releases/releases/download/v${obsidian_ver}/${obsidian_deb}"

apt_packages="libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libsecret-1-0 libgbm-dev libasound2-dev build-essential"
pkg_list="debootstrap"

chroot_mount_points="
/proc
/sys
/dev
/dev/fd
/dev/shm
/tmp
"

bail()
{
	if [ $# -gt 0 ]; then
		echo "${0##*/}: Error: $*" >&2
	fi
	exit 1
}

mk_mount_dirs()
{
	local dir p
	for p in ${chroot_mount_points}; do
		dir="${chroot_path}/$p"
		[ ! -d "${dir}" ] && mkdir -p "${dir}"
	done
}

umount_chroot()
{
	local mntpts _chroot_path p _p

	_chroot_path=$(realpath "${chroot_path}")
	[ $? -ne 0 -o -z "${_chroot_path}" ] && exit 1
	mntpts=$(mount -p | awk -F'[ \t]+' -v chroot=${_chroot_path} '
		$2 ~ sprintf("^%s/", chroot) {
			mp[n++] = $2
		}
		END {
			while (--n >= 0) print mp[n]
		}
	')
	for p in ${mntpts}; do
		_p=$(realpath "$p")
		[ $? -ne 0 -o -z "${_p}" ] && exit 1
		umount "${_p}" || exit 1
		if (mount -p | grep -q "${_p}/"); then
			bail "Couldn't unmount ${_p}"
		fi
	done
}

install_rc()
{
	install -m 555 rc.d/ubuntu "${prefix}/etc/rc.d"
}

install_steam_utils()
{
	pkg info --exists linux-steam-utils && return
	pkg fetch -y -o /tmp linux-steam-utils || exit 1

	pkgpath=/tmp/All/linux-steam-utils-*.pkg
	[ ! -f ${pkgpath} ] && pkgpath=/tmp/All/linux-steam-utils-*.txz
	[ ! -f ${pkgpath} ] && exit 1
	(cd / && tar -xf ${pkgpath} \
		--exclude '^+COMPACT_MANIFEST' \
		--exclude '^+MANIFEST')
}

install_packages()
{
	for p in ${pkg_list}; do
		pkg info --exists $p && continue
		pkg install -y $p || bail "'pkg install -y $p' failed"
	done
}

fix_ld_path()
{
	# 64 bit
	(cd ${chroot_path}/lib64 && \
		(unlink ./ld-linux-x86-64.so.2; \
			ln -s ../lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 \
			ld-linux-x86-64.so.2))

	# 32 bit
	(cd ${chroot_path}/lib && \
		(unlink ./ld-linux.so.2; \
			ln -s ../lib32/ld-linux.so.2 ld-linux-so.2))

}

install_apt_packages()
{
	chroot ${chroot_path} /bin/bash -c 'apt update'
	chroot ${chroot_path} /bin/bash -c 'apt remove -y rsyslog'
	for p in ${apt_packages}; do
		chroot ${chroot_path} /bin/bash -c "apt install -y $p" || \
			bail "'apt install -y $p' failed"
	done
}

build_scripts()
{
	for s in $(find bin chroot/bin rc.d -name "*.in"); do
		sed -E "s#@CHROOT_PATH@#${chroot_path}#g" < $s > ${s%.in}
	done
}


install_obsidian()
{
	if [ -x ${chroot_path}/opt/Obsidian/obsidan ]; then
		echo "Obsidian already installed" >&2
		exit 1
	fi

	install_libbsd_kmod

	fetch -o ${chroot_path} "${obsidian_url}"

	chroot ${chroot_path} /bin/bash -c "apt update"
	chroot ${chroot_path} /bin/bash -c "dpkg -i /${obsidian_deb}"

#	[ -d "${chroot_path}/${prefix}/share/fonts" ] && \
#		rmdir "${chroot_path}/${prefix}/share/fonts"

	install -m 555 chroot/bin/obsidian "${chroot_bindir}"
	install -m 555 bin/linux-obsidian "${bindir}"

	install -m 644 chroot/lib/x86_64-linux-gnu/libbsd-compat.a "${chroot_libx86_64dir}"
	install -m 644 chroot/lib/x86_64-linux-gnu/libbsd.a "${chroot_libx86_64dir}"
	install -m 644 chroot/lib/x86_64-linux-gnu/libbsd.so "${chroot_libx86_64dir}"
	install -m 644 chroot/lib/x86_64-linux-gnu/libbsd.so.1 "${chroot_libx86_64dir}"
	install -m 644 chroot/lib/x86_64-linux-gnu/libbsd_p.a "${chroot_libx86_64dir}"

	install -m 644 chroot/lib64/libinotify.a "${chroot_lib64dir}"
	install -m 644 chroot/lib64/libinotify.la "${chroot_lib64dir}"
	install -m 644 chroot/lib64/libinotify.so "${chroot_lib64dir}"
	install -m 644 chroot/lib64/libinotify.so.0 "${chroot_lib64dir}"
	install -m 644 chroot/lib64/libinotify.so.0.0.0 "${chroot_lib64dir}"

#	install -m 0644 linux-chrome.desktop "${appsdir}"

}

install_libbsd_kmod()
{
	local _libbsd_dir

	currentdir=$(pwd)

	kldstat -n "${libbsd_kmod}" && return

	mkdir -p "${libbsd_dir}"

	_libbsd_dir=$(realpath "${libbsd_dir}")
	git clone "${libbsd_repo}" "${_libbsd_dir}"

	cd "${_libbsd_dir}/kmod"
	make
	make install

	kldload "${libbsd_kmod}"

	cd $currentdir

	return
}

deinstall_obsidian()
{
	chroot ${chroot_path} /bin/bash -c "apt remove -y obsidian" || \
		bail "'apt remove -y obsidian' failed"
#	rm -f "${appsdir}/linux-chrome.desktop"
	rm -f "${bindir}/linux-obsidian"
	rm -f "${chroot_bindir}/obsidian"
}

symlink_icons()
{
	local name i
	[ ! -d ${chroot_path}/usr/share/icons ] && \
		mkdir -p ${chroot_path}/usr/share/icons
	for i in ${prefix}/share/icons/*; do
		[ ! -d $i ] && continue
		name=$(basename $i)
		[ -e ${chroot_path}/usr/share/icons/${name} ] && continue
		ln -s $i ${chroot_path}/usr/share/icons
	done
}

symlink_themes()
{
	local name i
	[ ! -d ${chroot_path}/usr/share/themes ] && \
		mkdir -p ${chroot_path}/usr/share/themes
	for i in ${prefix}/share/themes/*; do
		[ ! -d $i ] && continue
		name=$(basename $i)
		[ -e ${chroot_path}/usr/share/themes/${name} ] && continue
		ln -s $i ${chroot_path}/usr/share/themes
	done
}

set_timezone()
{
	printf "0.0 0 0.0\n0\nUTC\n" > ${chroot_path}/etc/adjtime
	if [ ! -d "${chroot_path}/etc/localtime" ]; then
		mkdir -p "${chroot_path}/etc/localtime"
	fi
	cp /var/db/zoneinfo "${chroot_path}/etc/timezone" \
		${chroot_path}/etc/localtime
	rm -f ${chroot_path}/etc/localtime
	ln -s "/usr/share/zoneinfo/$(cat /var/db/zoneinfo)" \
		${chroot_path}/etc/localtime
	chroot ${chroot_path} /bin/bash -c \
		"dpkg-reconfigure --frontend noninteractive tzdata"
}

install_chroot_base()
{
	[ -f ${chroot_path}/etc/os-release ] && return
	mk_mount_dirs
	install_rc
	sysrc linux_enable=NO
	sysrc ubuntu_enable=YES
	service ubuntu start || bail "Failed to start ubuntu service"
	install_steam_utils
	install_packages
	debootstrap --arch=amd64 --no-check-gpg ${ubuntu_version} ${chroot_path} || \
		bail "debootstrap failed"
	echo "APT::Cache-Start 251658240;" > \
		${chroot_path}/etc/apt/apt.conf.d/00aptitude
	echo "deb http://archive.ubuntu.com/ubuntu/ ${ubuntu_version} " \
	     "main restricted universe multiverse" > \
		${chroot_path}/etc/apt/sources.list
	fix_ld_path
	set_timezone
	service ubuntu start
	install_apt_packages
	symlink_icons
	symlink_themes
}

deinstall_chroot_base()
{
	local path
	path=$(realpath ${chroot_path})
	[ $? -ne 0 ] && exit 1

	if [ "${path}" = "/" ]; then
		echo "chroot_path must not be '/'" >&2
		exit 1
	fi
	umount_chroot
	rm -rf "${path}"
	rm -f "${prefix}/etc/rc.d/ubuntu"
	sysrc -x ubuntu_enable
}

upgrade_chroot()
{
	local flags="-q -y --allow-downgrades"
	flags="${flags} --allow-remove-essential --allow-change-held-packages"
	chroot ${chroot_path} /bin/bash -c "apt-get update && apt upgrade ${flags}"
}

cleanup()
{
	rm -f "bin/linux-obsidian"
	rm -f "chroot/bin/obsidian"
	rm -f rc.d/ubuntu
}

usage()
{
	echo "Usage: $0 install"
	echo "       $0 deinstall"
	echo "       $0 chroot <create|upgrade|delete>"
	echo "       $0 symlink <icons|themes>"
	echo "       $0 clean"
	exit 1
}

if [ $(id -u) -ne 0 ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

[ $# -eq 0 ] && usage

while [ $# -gt 0 ]; do
	case "$1" in
	install)
		build_scripts
		install_chroot_base
		eval install_obsidian
		;;
	deinstall)
		eval deinstall_obsidian
		exit 0
		;;
	clean)
		cleanup
		exit 0
		;;
	chroot|jail)
		case $2 in
		create)
			build_scripts
			install_chroot_base
			exit 0
			;;
		delete)
			deinstall_chroot_base
			exit 0
			;;
		upgrade)
			upgrade_chroot
			exit 0
			;;
		*)
			usage
			;;
		esac
		shift
		;;
	symlink)
		case $2 in
		icons|themes)
			eval symlink_$2
			exit 0
			;;
		*)
			usage
			;;
		esac
		shift
		;;
	*)
		usage
		;;
	esac
	shift
done

